# TRACKING
# Initiative:
# Feature:
# Author:
# Status: draft | accepted | implemented

# CONTRACT
# Given the user can ...
# The system must ...
# Success means ...

# CONSTRAINTS
# Must not ...
# Assumed preconditions: ...

# SEQUENCING
# Depends on: (feature names or none)
# Blocks: (feature names or none)

# NFR
# Performance: ...
# Reliability: ...
# Security: ...

# SIDE EFFECTS
# Produces: ...
# Modifies: ...
# Notifies: ...

# SCOPE
# In scope: ...
# Out of scope: ...

Feature: <name>

  # <feature-name>-001
  Scenario: <scenario name>
    Given ...
    When ...
    Then ...
